# Generated by Django 6.0.2 on 2026-03-23 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_question_created_by_question_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='expiry_date',
        ),
    ]
